### PR TITLE
Mapnik 3.4.1

### PR DESCRIPTION
**Pull request by flippmoke**

### CODE REVIEW

**Comment by rochoa** [comment]
Any plan on merging this? And more important: is this an expected regression? Or is a fixed bug in mapnik?

Currently tests only work in master with mapnik<3.4.1.

```shell
$ make clean all; npm install mapnik@3.4.0; make test
...
  36 passing (2s)
```

```shell
$ make clean all; npm install mapnik@3.4.1; make test
...
  31 passing (2s)
  5 failing
...
```
^^ Grids and tiles mismatching.

**Comment by rochoa** [comment]
Thanks a lot for the merge! But could you explain what the problem was? :innocent:

**Comment by flippmoke** [comment]
Something deep in mapnik caused very slight differences in the results in an expected way, because mapnik 3.4.1 was built against a different version then 3.4.0

**Comment by rochoa** [comment]
OK :laughing: Thank you @flippmoke!

**Pull request merged**
